CREATE TABLE venda(
	cliente VARCHAR(14) NOT NULL,
	datavenda DATE NOT NULL,
	status VARCHAR NOT NULL,
	valor DECIMAL(10,2) NOT NULL, 
	PRIMARY KEY (cliente)
);
CREATE TABLE cliente(
	nome VARCHAR NOT NULL,
	cnpj VARCHAR(14) NOT NULL,
	email VARCHAR NOT NULL,
	Telefone VARCHAR NOT NULL,
	UF VARCHAR NOT NULL,
	localização VARCHAR NOT NULL,
	PRIMARY KEY (cnpj)
);