CREATE TABLE venda(
	cliente VARCHAR(14) NOT NULL,
	datavenda DATE NOT NULL,
	status VARCHAR NOT NULL,
	valor INTEGER NOT NULL
);
CREATE TABLE cliente(
	nome VARCHAR NOT NULL,
	CNPJ VARCHAR(14) NOT NULL,
	email VARCHAR NOT NULL,
	Telefone VARCHAR NOT NULL,
	UF VARCHAR NOT NULL,
	localização VARCHAR NOT NULL
);